package com.caregiverproca.app.content

/**
 * The full 90-day / 13-week curriculum, verbatim from
 * 02_PRODUCT_CONTENT/CURRICULO_90_DIAS.csv. Generated from the CSV with a
 * script (not hand-typed) to avoid transcription errors across 90 rows.
 *
 * `criticalSafety = true` marks a day whose content touches a safety-critical
 * topic (911, abuse reporting, medication scope, mobility limits, etc.) —
 * per LEARNING_ENGINE_SPEC.md these days get "fallos críticos internos"
 * treatment in scenarios, distinct from ordinary review items.
 */
data class CurriculumDay(
    val day: Int,
    val week: Int,
    val moduleId: String,
    val titleEs: String,
    val objectiveEs: String,
    val practiceEs: String,
    val evidence: String,
    val criticalSafety: Boolean,
    val sourceTags: List<String>,
)

/** Spanish display name per module (one module = one week, in this curriculum). */
val ModuleTitlesEs: Map<String, String> = mapOf(
    "foundations" to "Fundamentos",
    "pathways" to "Rutas de California",
    "infection" to "Control de Infecciones",
    "safety" to "Seguridad y Emergencias",
    "adl" to "Actividades de la Vida Diaria",
    "mobility" to "Movilidad y Transferencias",
    "nutrition" to "Nutrición y Alimentación",
    "dementia" to "Apoyo Cognitivo y Demencia",
    "communication" to "Comunicación Bilingüe",
    "documentation" to "Documentación y Entrega de Turno",
    "abuse" to "Reporte de Abuso",
    "medication_support" to "Apoyo con Medicamentos",
    "career" to "Carrera y Evaluación Final",
)

val Curriculum: List<CurriculumDay> = listOf(
    CurriculumDay(1, 1, "foundations", "Propósito y límites del curso", "Distinguir formación interna de una credencial estatal", "Clasificar cinco afirmaciones como educación, registro o certificación", "quiz+reflection", false, listOf("disclaimer")),
    CurriculumDay(2, 1, "foundations", "Dignidad y enfoque centrado en la persona", "Reconocer preferencias y capacidades antes de ayudar", "Reescribir órdenes como opciones respetuosas", "response+rubric", false, listOf("ethics")),
    CurriculumDay(3, 1, "foundations", "Consentimiento antes de ayudar", "Pedir permiso y aceptar una pausa o rechazo seguro", "Practicar tres frases de consentimiento en español e inglés", "roleplay+audio", false, listOf("care_plan")),
    CurriculumDay(4, 1, "foundations", "Privacidad y confidencialidad", "Proteger conversaciones, cuerpo, hogar e información", "Detectar seis violaciones de privacidad en una escena ficticia", "scenario+quiz", false, listOf("privacy")),
    CurriculumDay(5, 1, "foundations", "Alcance no médico", "Separar ayuda permitida de diagnóstico, prescripción o tareas no autorizadas", "Ordenar acciones en hacer, verificar o escalar", "classification+review", true, listOf("HSC_1796_12")),
    CurriculumDay(6, 1, "foundations", "Límites profesionales", "Identificar conflictos, regalos, dinero y relaciones duales", "Responder a un ofrecimiento de préstamo sin avergonzar al cliente", "scenario+rubric", false, listOf("employer_policy")),
    CurriculumDay(7, 1, "foundations", "Usar el plan de cuidado", "Consultar instrucciones individuales y registrar dudas", "Localizar tarea, preferencia, riesgo y contacto de escalamiento en un plan ficticio", "assessment+spaced_review", true, listOf("care_plan")),
    CurriculumDay(8, 2, "pathways", "Mapa de rutas de California", "Diferenciar cuidador familiar, IHSS, HCA/HCO, privado, HHA y CNA", "Elegir la ruta correcta para seis perfiles ficticios", "classification+quiz", false, listOf("pathways")),
    CurriculumDay(9, 2, "pathways", "Ruta del cuidador familiar", "Explicar por qué no existe una credencial universal para todo cuidador familiar", "Crear un plan de límites y contactos para apoyo informal", "plan+reflection", false, listOf("ca_aging")),
    CurriculumDay(10, 2, "pathways", "Inscripción IHSS", "Recordar SOC 426, orientación, SOC 846 y antecedentes DOJ", "Ordenar los cuatro pasos sin introducir datos reales", "sequence+review", false, listOf("CDSS_IHSS")),
    CurriculumDay(11, 2, "pathways", "HCA afiliado a una HCO", "Identificar registro, cinco horas iniciales, formación anual y TB", "Construir una lista por momento: antes del cliente, anual y seguimiento", "quiz+checklist", false, listOf("HSC_1796_44", "HSC_1796_45")),
    CurriculumDay(12, 2, "pathways", "Cuidador privado o directo", "Distinguir acuerdo directo de afiliación HCO e IHSS", "Marcar qué asuntos requieren contrato, fuente oficial o asesoría", "scenario+reflection", false, listOf("HSC_1796_14", "HSC_1796_15")),
    CurriculumDay(13, 2, "pathways", "HHA y CNA no son lo mismo", "Comparar programas aprobados y límites de esta app", "Completar tabla 120 h HHA, 40 h elegible y 160 h CNA", "comparison+quiz", false, listOf("CDPH_HHA", "CDPH_CNA")),
    CurriculumDay(14, 2, "pathways", "Comprobar una fuente oficial", "Evaluar agencia, jurisdicción, fecha y aplicabilidad", "Auditar una tarjeta de requisito desactualizada", "source_audit+review", false, listOf("source_governance")),
    CurriculumDay(15, 3, "infection", "Cómo se transmite una infección", "Reconocer cadena de transmisión sin diagnosticar", "Identificar puntos para cortar transmisión en un hogar ficticio", "diagram+quiz", false, listOf("infection_control")),
    CurriculumDay(16, 3, "infection", "Momentos de higiene de manos", "Elegir cuándo limpiar las manos según tarea y riesgo", "Secuenciar preparación, cuidado y limpieza", "scenario+review", true, listOf("infection_control")),
    CurriculumDay(17, 3, "infection", "Uso responsable de guantes y PPE", "Entender que los guantes no sustituyen higiene ni política", "Detectar contaminación cruzada en cuatro decisiones", "scenario+rubric", true, listOf("employer_policy")),
    CurriculumDay(18, 3, "infection", "Limpieza de superficies", "Seguir etiqueta, ventilación y plan sin mezclar químicos", "Elegir una respuesta segura ante productos incompatibles", "quiz+checklist", true, listOf("product_label", "care_plan")),
    CurriculumDay(19, 3, "infection", "Ropa, residuos y objetos personales", "Reducir exposición y preservar dignidad", "Planear manipulación sin sacudir ni mezclar objetos personales", "response+review", false, listOf("infection_control")),
    CurriculumDay(20, 3, "infection", "Etiqueta respiratoria y enfermedad", "Aplicar medidas del plan y escalar síntomas observados", "Practicar un reporte objetivo al supervisor", "handoff+audio", true, listOf("care_plan", "employer_policy")),
    CurriculumDay(21, 3, "infection", "Caso integrado de control de infección", "Combinar higiene, PPE, limpieza y comunicación", "Resolver un escenario ramificado y reintentar fallos", "scenario+assessment", true, listOf("infection_control")),
    CurriculumDay(22, 4, "safety", "Recorrido de seguridad del hogar", "Observar riesgos sin modificar el hogar sin permiso", "Documentar iluminación, cables, alfombras y salidas como hechos", "checklist+photo_free_note", false, listOf("care_plan")),
    CurriculumDay(23, 4, "safety", "Plan de emergencia y contactos", "Localizar dirección, contactos, salida y equipo autorizado", "Completar un plan ficticio sin datos personales", "plan+quiz", true, listOf("emergency")),
    CurriculumDay(24, 4, "safety", "Cuándo llamar al 911", "Priorizar peligro inmediato sobre temporizador o documentación", "Elegir acción inicial en seis situaciones", "critical_scenario+review", true, listOf("911")),
    CurriculumDay(25, 4, "safety", "Prevención de caídas", "Reducir riesgos respetando movilidad y autonomía", "Proponer cambios y pedir consentimiento antes de actuar", "scenario+rubric", true, listOf("care_plan")),
    CurriculumDay(26, 4, "safety", "Atragantamiento: reconocer y activar ayuda", "Reconocer una emergencia y usar formación presencial aplicable", "Distinguir tos efectiva, obstrucción grave y necesidad de 911 sin simular certificación", "quiz+hands_on_notice", true, listOf("911", "CPR_training")),
    CurriculumDay(27, 4, "safety", "Fuego, humo, calor y electricidad", "Seguir salida segura y plan de emergencia", "Seleccionar ruta de evacuación en escenario ficticio", "scenario+checklist", true, listOf("emergency")),
    CurriculumDay(28, 4, "safety", "Evaluación de seguridad", "Integrar observación, acción inmediata y escalamiento", "Completar evaluación sin usar ayuda durante el primer intento", "assessment+spaced_review", true, listOf("emergency")),
    CurriculumDay(29, 5, "adl", "Ayudar sin quitar independencia", "Usar la menor ayuda segura necesaria", "Convertir cuatro tareas en indicación, preparación o asistencia", "classification+reflection", false, listOf("person_centered")),
    CurriculumDay(30, 5, "adl", "Baño, elección y rechazo", "Responder a rechazo sin coacción y revisar riesgos/plan", "Role-play de ofrecer opciones y escalar una preocupación", "roleplay+rubric", true, listOf("consent", "care_plan")),
    CurriculumDay(31, 5, "adl", "Vestido y preferencias", "Apoyar elección, privacidad y ritmo", "Preparar una secuencia de ayuda centrada en la persona", "sequence+review", false, listOf("ADL")),
    CurriculumDay(32, 5, "adl", "Toileting y dignidad", "Proteger privacidad, seguridad y control de infección", "Detectar lenguaje y acciones que deben cambiar", "scenario+quiz", true, listOf("ADL", "infection_control")),
    CurriculumDay(33, 5, "adl", "Cuidado oral y observación de piel", "Observar y reportar cambios sin diagnosticar ni tratar", "Redactar una nota de hechos visibles y malestar reportado", "documentation+rubric", true, listOf("scope", "care_plan")),
    CurriculumDay(34, 5, "adl", "Rutina, descanso y sueño", "Apoyar rutinas documentadas y notar cambios", "Planear una conversación sobre preferencias de descanso", "response+audio", false, listOf("care_plan")),
    CurriculumDay(35, 5, "adl", "Caso integrado de actividades diarias", "Combinar consentimiento, privacidad, seguridad y alcance", "Resolver un turno matutino ficticio con varias decisiones", "scenario+assessment", true, listOf("ADL")),
    CurriculumDay(36, 6, "mobility", "Movilidad y elección", "Preguntar cómo prefiere moverse y seguir el plan", "Practicar indicaciones breves antes de ofrecer contacto", "roleplay+review", false, listOf("care_plan")),
    CurriculumDay(37, 6, "mobility", "Entorno, calzado y ayudas", "Revisar condiciones y equipo autorizado", "Identificar cinco riesgos sin mover pertenencias sin permiso", "checklist+quiz", true, listOf("fall_prevention")),
    CurriculumDay(38, 6, "mobility", "Mecánica corporal del cuidador", "Proteger al usuario y al cuidador sin improvisar", "Reconocer cuándo detenerse y pedir segunda persona o equipo", "scenario+reflection", true, listOf("hands_on")),
    CurriculumDay(39, 6, "mobility", "Límites de las transferencias", "No ejecutar una transferencia no entrenada o fuera del plan", "Elegir entre asistir, pausar o escalar", "critical_scenario+rubric", true, listOf("hands_on", "care_plan")),
    CurriculumDay(40, 6, "mobility", "Grúas y equipos de movilidad", "Entender que la app no acredita uso de equipos", "Completar checklist previo y marcar verificación presencial requerida", "checklist+signoff_required", true, listOf("hands_on")),
    CurriculumDay(41, 6, "mobility", "Respuesta después de una caída", "Proteger seguridad, no improvisar levantamiento y activar ayuda según condición/plan", "Ordenar acciones en un escenario de caída con posible lesión", "critical_scenario+review", true, listOf("911", "care_plan")),
    CurriculumDay(42, 6, "mobility", "Evaluación de movilidad segura", "Integrar consentimiento, entorno, límites y escalamiento", "Resolver escenario y solicitar firma de observación separada", "assessment+signoff_optional", true, listOf("hands_on")),
    CurriculumDay(43, 7, "nutrition", "Plan, preferencias y dieta indicada", "Seguir preferencias y restricciones documentadas sin prescribir", "Distinguir elección personal, orden del plan y cambio que requiere consulta", "classification+quiz", true, listOf("care_plan")),
    CurriculumDay(44, 7, "nutrition", "Observar hidratación", "Ofrecer líquidos permitidos y reportar cambios observables", "Registrar ingesta ficticia y una preocupación sin diagnosticar", "documentation+review", false, listOf("scope")),
    CurriculumDay(45, 7, "nutrition", "Preparación de comidas segura", "Prevenir contaminación y respetar restricciones", "Secuenciar lavado, separación, cocción y almacenamiento", "sequence+quiz", true, listOf("food_safety")),
    CurriculumDay(46, 7, "nutrition", "Compras y presupuesto con límites", "Manejar listas, recibos y dinero con transparencia", "Resolver discrepancia de recibo sin mezclar fondos", "scenario+rubric", false, listOf("boundaries")),
    CurriculumDay(47, 7, "nutrition", "Dificultad al tragar y señales de alarma", "Observar, detener la ayuda insegura y escalar según plan; 911 ante emergencia", "Responder a tos/cambio repentino sin cambiar textura por cuenta propia", "critical_scenario+review", true, listOf("911", "care_plan")),
    CurriculumDay(48, 7, "nutrition", "Comidas con dignidad y autonomía", "Dar tiempo, opciones y la ayuda mínima necesaria", "Role-play bilingüe durante una comida", "roleplay+audio", false, listOf("person_centered")),
    CurriculumDay(49, 7, "nutrition", "Caso integrado de nutrición", "Combinar plan, seguridad alimentaria, observación y límites", "Completar caso ramificado de una comida y documentar", "scenario+assessment", true, listOf("food_safety", "care_plan")),
    CurriculumDay(50, 8, "dementia", "Lenguaje centrado en la persona", "Separar a la persona de un diagnóstico o conducta", "Reformular cinco etiquetas estigmatizantes", "response+quiz", false, listOf("dementia")),
    CurriculumDay(51, 8, "dementia", "Comunicación calmada y simple", "Usar una idea por vez, tiempo y validación", "Grabar tres respuestas cortas en español e inglés", "roleplay+audio", false, listOf("dementia")),
    CurriculumDay(52, 8, "dementia", "Rutinas y señales del entorno", "Apoyar previsibilidad sin controlar innecesariamente", "Diseñar una rutina ficticia basada en preferencias", "plan+review", false, listOf("care_plan")),
    CurriculumDay(53, 8, "dementia", "La conducta comunica una necesidad", "Observar desencadenantes y necesidades sin diagnosticar", "Completar antecedente, hecho observable y respuesta segura", "scenario+rubric", true, listOf("scope")),
    CurriculumDay(54, 8, "dementia", "Salida no planificada y seguridad", "Aplicar plan, supervisión autorizada y escalamiento inmediato", "Resolver un escenario de puerta abierta sin restricción improvisada", "critical_scenario+review", true, listOf("emergency", "care_plan")),
    CurriculumDay(55, 8, "dementia", "Cambio repentino no es rutina", "Tratar un cambio agudo como preocupación que requiere escalamiento", "Comunicar inicio, hechos y diferencia respecto a la línea base", "handoff+quiz", true, listOf("scope", "emergency")),
    CurriculumDay(56, 8, "dementia", "Caso integrado de apoyo cognitivo", "Usar validación, opciones, seguridad y documentación", "Completar escenario y autoevaluar tono y claridad", "scenario+assessment", true, listOf("dementia")),
    CurriculumDay(57, 9, "communication", "Escucha activa", "Reflejar necesidad y comprobar comprensión", "Responder sin interrumpir ni asumir", "roleplay+rubric", false, listOf("communication")),
    CurriculumDay(58, 9, "communication", "Lenguaje claro y una instrucción a la vez", "Reducir jerga y carga cognitiva", "Simplificar seis frases de cuidado", "rewrite+review", false, listOf("communication")),
    CurriculumDay(59, 9, "communication", "Teach-back sin examen", "Comprobar cómo explicaste, no culpar al oyente", "Practicar una invitación respetuosa a repetir el plan", "roleplay+audio", false, listOf("communication")),
    CurriculumDay(60, 9, "communication", "Apoyo bilingüe y límites", "Reconocer cuándo el idioma propio no basta y pedir apoyo autorizado", "Elegir respuesta ante información compleja o sensible", "scenario+quiz", true, listOf("language_access")),
    CurriculumDay(61, 9, "communication", "Frases esenciales de turno en inglés", "Comunicar observación, acción y pendiente con lenguaje sencillo", "Shadowing a velocidad lenta y normal", "audio+recording", false, listOf("bilingual")),
    CurriculumDay(62, 9, "communication", "Pronunciación y aclaración segura", "Pedir repetición, deletreo o confirmación sin fingir entender", "Grabar y comparar cinco frases funcionales", "audio+rubric", false, listOf("bilingual")),
    CurriculumDay(63, 9, "communication", "Role-play bilingüe completo", "Mantener dignidad, alcance y exactitud entre idiomas", "Completar conversación ramificada y reintento", "scenario+assessment", true, listOf("bilingual")),
    CurriculumDay(64, 10, "documentation", "Hechos, no diagnósticos", "Documentar lo observado, oído y realizado", "Corregir notas con juicios o diagnósticos", "rewrite+quiz", true, listOf("scope")),
    CurriculumDay(65, 10, "documentation", "Hora, secuencia y exactitud", "Registrar cronología sin alterar ni rellenar memoria", "Ordenar eventos y marcar dato desconocido", "timeline+review", false, listOf("documentation")),
    CurriculumDay(66, 10, "documentation", "DAR y SOAP como técnicas de práctica", "Usar estructuras solo cuando el empleador las acepte", "Convertir hechos en dos formatos y comparar límites", "documentation+rubric", false, listOf("employer_policy")),
    CurriculumDay(67, 10, "documentation", "Medicamentos: registrar sin inventar", "Seguir plan/formato autorizado y no corregir un registro de memoria", "Resolver una discrepancia escalando antes de firmar", "critical_scenario+quiz", true, listOf("medication_scope")),
    CurriculumDay(68, 10, "documentation", "Entrega de turno estructurada", "Comunicar situación, hechos, acciones y pendiente", "Realizar una entrega de 60 segundos", "audio+rubric", true, listOf("handoff")),
    CurriculumDay(69, 10, "documentation", "Privacidad al comunicar", "Usar canal, audiencia y contenido mínimos", "Elegir dónde y con quién compartir una actualización", "scenario+review", true, listOf("privacy")),
    CurriculumDay(70, 10, "documentation", "Simulación completa de turno", "Integrar cuidado, notas y entrega sin omisiones internas", "Completar un turno ficticio; cero omisiones es criterio de la simulación", "scenario+assessment", true, listOf("handoff")),
    CurriculumDay(71, 11, "abuse", "Tipos de abuso, neglect y explotación", "Reconocer categorías sin investigar ni confrontar", "Clasificar señales ficticias y separar hecho de inferencia", "classification+quiz", true, listOf("WIC_15630")),
    CurriculumDay(72, 11, "abuse", "Señales y sospecha razonable", "Entender que no se necesita prueba definitiva para activar el deber aplicable", "Decidir qué observación requiere reporte o consulta inmediata", "scenario+review", true, listOf("WIC_15630")),
    CurriculumDay(73, 11, "abuse", "Quién puede ser reportante obligatorio", "Relacionar responsabilidad de cuidado con la definición legal y el entorno", "Evaluar perfiles ficticios sin dar asesoría legal personalizada", "quiz+source_check", true, listOf("WIC_15630")),
    CurriculumDay(74, 11, "abuse", "Peligro inmediato, APS y policía", "Elegir 911 ante peligro y canal apropiado para reporte en el hogar", "Resolver cuatro ramas con ubicación ficticia", "critical_scenario+rubric", true, listOf("WIC_15630", "APS")),
    CurriculumDay(75, 11, "abuse", "Tiempo y seguimiento del reporte", "Recordar inmediato/tan pronto como sea posible y seguimiento en dos días laborables tras teléfono", "Construir línea de tiempo de un reporte ficticio", "timeline+quiz", true, listOf("WIC_15630")),
    CurriculumDay(76, 11, "abuse", "Documentar sin investigar", "Registrar palabras exactas y hechos sin prometer secreto", "Reescribir una nota que confronta al presunto agresor", "rewrite+review", true, listOf("WIC_15630")),
    CurriculumDay(77, 11, "abuse", "Caso integrado de reporte", "Proteger, reportar y documentar según entorno", "Completar caso crítico y localizar fuente oficial", "scenario+assessment", true, listOf("WIC_15630", "APS")),
    CurriculumDay(78, 12, "medication_support", "Medicamentos autoadministrados y alcance", "Distinguir asistencia permitida de prescribir, decidir o cambiar dosis", "Clasificar ocho acciones en ayudar, verificar o escalar", "classification+quiz", true, listOf("HSC_1796_12")),
    CurriculumDay(79, 12, "medication_support", "Seguir el plan y la etiqueta", "Comparar instrucciones autorizadas sin interpretar cambios", "Responder a una etiqueta y plan que no coinciden", "critical_scenario+review", true, listOf("care_plan")),
    CurriculumDay(80, 12, "medication_support", "Dosis omitida o rechazo", "No forzar, duplicar ni decidir; observar y escalar según plan", "Role-play de respuesta y notificación", "scenario+rubric", true, listOf("medication_scope")),
    CurriculumDay(81, 12, "medication_support", "Cambios observables y efectos reportados", "Comunicar hechos y palabras de la persona sin diagnosticar", "Preparar llamada estructurada con hora, hecho y acción", "handoff+audio", true, listOf("scope")),
    CurriculumDay(82, 12, "medication_support", "Apoyo a condiciones crónicas", "Seguir rutinas autorizadas y reconocer límites", "Elegir apoyo no médico y cuándo llamar ayuda", "scenario+quiz", true, listOf("care_plan")),
    CurriculumDay(83, 12, "medication_support", "Citas y comunicación con el equipo", "Preparar observaciones/preguntas sin hablar por la persona innecesariamente", "Crear lista breve centrada en preferencias", "plan+reflection", false, listOf("consent", "privacy")),
    CurriculumDay(84, 12, "medication_support", "Caso integrado de apoyo con medicación", "Combinar plan, rechazo, observación y escalamiento", "Resolver caso crítico sin tomar decisiones clínicas", "scenario+assessment", true, listOf("HSC_1796_12")),
    CurriculumDay(85, 13, "career", "Confirmar mi ruta", "Elegir una ruta y reconocer cuándo debe cambiar", "Actualizar perfil y explicar la elección con dos fuentes", "pathway_check+reflection", false, listOf("pathways")),
    CurriculumDay(86, 13, "career", "Checklist oficial de próximos pasos", "Separar tareas dentro de la app de acciones con agencia, condado o programa", "Crear lista fechada con enlaces oficiales", "plan+source_check", false, listOf("official_resources")),
    CurriculumDay(87, 13, "career", "Guardian e IHSS: procesos distintos", "Explicar diferencias sin compartir datos sensibles", "Comparar solicitud HCA con inscripción IHSS", "comparison+quiz", false, listOf("CDSS_HCA", "CDSS_IHSS")),
    CurriculumDay(88, 13, "career", "Comparar HHA y CNA", "Elegir preguntas para un programa aprobado y reconocer horas supervisadas", "Auditar una publicidad ficticia de escuela", "source_audit+rubric", false, listOf("CDPH_HHA", "CDPH_CNA")),
    CurriculumDay(89, 13, "career", "Portafolio, entrevista y autocuidado", "Presentar aprendizaje honestamente y planificar límites saludables", "Redactar logro sin afirmar credencial y una pregunta de entrevista", "portfolio+reflection", false, listOf("career")),
    CurriculumDay(90, 13, "career", "Evaluación final interna y plan de continuidad", "Integrar seguridad, alcance, comunicación, reporte y ruta profesional", "Completar evaluación, revisar errores y crear próximos pasos oficiales", "final_assessment+spaced_review", true, listOf("all")),
)

fun curriculumDayFor(day: Int): CurriculumDay? = Curriculum.firstOrNull { it.day == day }
fun curriculumWeek(week: Int): List<CurriculumDay> = Curriculum.filter { it.week == week }
