package com.caregiverproca.app.content

/** Verbatim from 02_PRODUCT_CONTENT/FLASHCARDS_SEED.json (39 cards across 13 weeks). */
data class Flashcard(
    val id: String,
    val week: Int,
    val questionEs: String,
    val answerEs: String,
    val sourceTags: List<String>,
    val critical: Boolean,
)

val Flashcards: List<Flashcard> = listOf(
    Flashcard("fc001", 1, "¿Qué credencial estatal entrega esta app?", "Ninguna. Puede emitir un certificado interno de finalización, claramente no gubernamental.", listOf("disclaimer"), true),
    Flashcard("fc002", 1, "¿Cuál es la regla corta del alcance?", "Seguir rol, formación, autorización y plan; observar y escalar en vez de diagnosticar o prescribir.", listOf("HSC_1796_12"), true),
    Flashcard("fc003", 1, "¿Qué haces ante un rechazo sin peligro inmediato?", "Reconocer la decisión, ofrecer opciones permitidas, documentar hechos y escalar según el plan.", listOf("consent", "care_plan"), false),
    Flashcard("fc004", 2, "¿Existe un examen HCA Guardian en el proceso CDSS citado?", "No. El proceso publicado describe cuenta, solicitud, PIN, tarifa y Live Scan/antecedentes.", listOf("CDSS_HCA"), true),
    Flashcard("fc005", 2, "¿Cuáles son cuatro pasos centrales de inscripción IHSS?", "SOC 426, orientación, SOC 846 y huellas/verificación DOJ, siguiendo al condado.", listOf("CDSS_IHSS"), false),
    Flashcard("fc006", 2, "¿HCA es licencia o registro?", "Registro. Usa “registro HCA” o “HCA registrado”, no licencia clínica.", listOf("CDSS_HCA"), true),
    Flashcard("fc007", 3, "¿Los guantes sustituyen la higiene de manos?", "No. Se usan según riesgo/política y se realiza higiene en los momentos indicados.", listOf("infection_control"), true),
    Flashcard("fc008", 3, "¿Qué es contaminación cruzada?", "Transferir microorganismos entre manos, objetos, superficies, alimentos o personas durante tareas.", listOf("infection_control"), false),
    Flashcard("fc009", 3, "¿Puedes mezclar limpiadores si quieres más potencia?", "No. Sigue etiqueta, ventilación, formación y política; no improvises mezclas.", listOf("product_label"), true),
    Flashcard("fc010", 4, "¿Qué pasa con el temporizador ante una emergencia?", "Se pausa o ignora. La seguridad inmediata y 911 tienen prioridad.", listOf("911"), true),
    Flashcard("fc011", 4, "¿Debes levantar de inmediato a alguien después de una caída?", "No improvises. Protege seguridad, evalúa peligro observable, sigue el plan y activa ayuda; 911 si corresponde.", listOf("care_plan", "911"), true),
    Flashcard("fc012", 4, "¿Una lección digital certifica respuesta a atragantamiento o CPR?", "No. Las habilidades manuales requieren formación y verificación práctica cualificada.", listOf("hands_on"), true),
    Flashcard("fc013", 5, "¿Qué hace objetiva una observación?", "Describe hora, lugar, aspecto, cantidad, conducta visible y palabras exactas sin juicio ni diagnóstico.", listOf("documentation"), false),
    Flashcard("fc014", 5, "¿Qué significa ayudar con la menor asistencia segura?", "Permitir que la persona haga lo que puede y ofrecer solo la pista, preparación o ayuda necesaria.", listOf("person_centered"), false),
    Flashcard("fc015", 5, "¿Un horario de baño elimina el consentimiento?", "No. Ofrece opciones, respeta el rechazo seguro y sigue el plan para documentar/escalar.", listOf("consent"), true),
    Flashcard("fc016", 6, "¿Qué haces si no fuiste entrenado con una grúa?", "No la uses por improvisación. Mantén seguridad y solicita ayuda/formación cualificada según el plan.", listOf("hands_on"), true),
    Flashcard("fc017", 6, "¿“Práctica completada” equivale a habilidad observada?", "No. La observación requiere evidencia separada y un verificador cualificado identificado.", listOf("competency"), false),
    Flashcard("fc018", 6, "¿Quién puede cambiar unilateralmente un requisito de dos personas en el plan?", "El alumno no. Debe detenerse y escalar al responsable autorizado.", listOf("care_plan"), true),
    Flashcard("fc019", 7, "¿Puede un cuidador cambiar por su cuenta una textura de dieta indicada?", "No. Pausa la ayuda insegura y consulta al responsable autorizado según el plan.", listOf("care_plan"), true),
    Flashcard("fc020", 7, "¿Cómo reportas una preocupación de hidratación?", "Con cantidades/horas observadas, cambios respecto a rutina y palabras de la persona; sin diagnosticar.", listOf("scope"), false),
    Flashcard("fc021", 7, "¿Qué haces si aparece peligro inmediato durante una comida?", "Detén la ayuda insegura y activa 911/plan de emergencia; no esperes al temporizador.", listOf("911"), true),
    Flashcard("fc022", 8, "¿Cómo se trata un cambio repentino respecto a la línea base?", "Como una preocupación nueva que requiere observación y escalamiento urgente según peligro y plan, no como “demencia normal”.", listOf("care_plan"), true),
    Flashcard("fc023", 8, "¿Qué puede comunicar una conducta?", "Una necesidad, emoción, dolor reportado, confusión, entorno o preferencia; observa patrones sin diagnosticar.", listOf("dementia"), false),
    Flashcard("fc024", 8, "¿Validar significa confirmar un hecho falso?", "No. Significa reconocer la emoción o necesidad sin discutir, engañar ni reforzar peligro.", listOf("communication"), false),
    Flashcard("fc025", 9, "¿Para qué sirve teach-back?", "Para comprobar si explicaste con claridad: invita a la otra persona a mostrar el plan con sus palabras, sin examinarla.", listOf("communication"), false),
    Flashcard("fc026", 9, "¿Qué haces si no entiendes una instrucción de seguridad en inglés?", "No adivines. Pide repetición, lenguaje sencillo, confirmación y apoyo lingüístico autorizado.", listOf("language_access"), true),
    Flashcard("fc027", 9, "¿La práctica de voz permite grabar a un cliente?", "No. Graba solo tu propia voz y nunca conversaciones de cuidado o información de salud.", listOf("privacy"), true),
    Flashcard("fc028", 10, "¿Qué debe incluir una entrega breve?", "Situación, hechos observables, acciones realizadas, respuesta y pendiente/persona notificada.", listOf("handoff"), false),
    Flashcard("fc029", 10, "¿DAR o SOAP son siempre formatos oficiales de CDSS para HCA?", "No. Son estructuras de práctica; usa el formato autorizado por empleador y plan.", listOf("documentation"), true),
    Flashcard("fc030", 10, "¿“Cero omisiones” es una política CDSS universal?", "No. Puede ser un criterio interno de una simulación, claramente rotulado como tal.", listOf("claim_correction"), true),
    Flashcard("fc031", 11, "¿Qué define WIC §15610.05?", "Abandono. No es la cita correcta para justificar autonomía o rechazo del baño.", listOf("WIC_15610_05"), true),
    Flashcard("fc032", 11, "¿Cuándo reporta una persona cubierta por WIC §15630?", "Por teléfono o Internet inmediatamente o tan pronto como sea posible; si fue por teléfono, seguimiento escrito/Internet dentro de dos días laborables.", listOf("WIC_15630"), true),
    Flashcard("fc033", 11, "¿Cuál es la línea estatal de APS que enruta por código postal?", "1-833-401-0832. Ante peligro inmediato, llama al 911.", listOf("APS"), true),
    Flashcard("fc034", 12, "¿Qué puede significar asistencia con medicación autoadministrada?", "Ayuda permitida por el plan sin diagnosticar, prescribir, seleccionar ni cambiar dosis, y sin tareas que requieren autoridad clínica.", listOf("HSC_1796_12"), true),
    Flashcard("fc035", 12, "¿Qué haces ante una dosis dudosa u omitida?", "No duplicas ni adivinas; sigues el plan y consultas al responsable autorizado.", listOf("medication_scope"), true),
    Flashcard("fc036", 12, "¿Qué datos no debe guardar la app?", "SSN, huellas o resultados, credenciales Guardian y PHI de clientes.", listOf("privacy"), true),
    Flashcard("fc037", 13, "¿Cuántas horas iniciales establece HSC §1796.44 para HCA afiliado?", "Cinco antes del cliente: dos de orientación y tres de seguridad; además, cinco anuales.", listOf("HSC_1796_44"), false),
    Flashcard("fc038", 13, "¿Cómo se distinguen las horas base CNA y HHA publicadas?", "CNA: 60 aula + 100 clínicas supervisadas. HHA: ruta base 120 h; opción aprobada 40 h para candidatos elegibles con CNA/formación aplicable.", listOf("CDPH_CNA", "CDPH_HHA"), true),
    Flashcard("fc039", 13, "¿Qué necesita una cifra de salario o beneficio en la app?", "Fuente, fecha, condado/ubicación, metodología y lenguaje de estimación; sin eso, no se publica.", listOf("claims_governance"), false),
)
